In [1]:
import pandas as pd

In [3]:
import numpy as np

In [5]:
import matplotlib as plt

In [7]:
print("abcd")

abcd


In [13]:
arr = [1,2,3,4,5,6,7]

for i in range (0,len(arr)):
    print(arr[i])
    

1
2
3
4
5
6
7


In [29]:
# creating an array
a = np.array([[1,2,3,4,5],
              [2,3,4,5,6]])
print (a)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [31]:
a.shape


(2, 5)

In [45]:
a

array([[1, 2],
       [3, 4],
       [5, 2],
       [3, 4],
       [5, 6]])

In [35]:
type(a)

numpy.ndarray

In [37]:
a.shape


(2, 5)

In [43]:
a.shape=(5,2)

In [49]:
a.shape

(5, 2)

In [51]:
a.size

10

In [63]:
a = a.reshape (2,5)

In [65]:
a


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [67]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [77]:
x = np.arange(1,100,9,dtype=float)
x

array([ 1., 10., 19., 28., 37., 46., 55., 64., 73., 82., 91.])