In [1]:
import numpy as np

In [5]:
n1 = np.array([[1,2],[3,4]])
n1

array([[1, 2],
       [3, 4]])

In [7]:
n2 = np.array([[3,4],[5,6]])
n2

array([[3, 4],
       [5, 6]])

### Transpose

In [10]:
np.transpose(n1)

array([[1, 3],
       [2, 4]])

### Dot Operation

In [13]:
n1.dot(n2)

array([[13, 16],
       [29, 36]])

### Inverse

In [16]:
np.linalg.inv(n1)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

### Determinant

In [19]:
np.linalg.det(n2)

-2.0000000000000004

### Flatten

In [22]:
n1.flatten()

array([1, 2, 3, 4])

### Read matrix from the user

In [25]:
matrix = []
for i in range(2):
    row = []
    for j in range(2):
        a = int(input())
        row.append(a)
    matrix.append(row)
print(matrix)

 1
 2
 3
 4


[[1, 2], [3, 4]]


In [34]:
np.transpose(matrix)

array([[2, 4],
       [3, 5]])

### Get row size and column size from the user
#### Method 1

In [28]:
m = int(input("Enter row size : "))
n = int(input("Enter column size : "))
matrix1 = []
for i in range(m):
    row = []
    for j in range(n):
        a = int(input())
        row.append(a)
    matrix1.append(row)
print(matrix1)

Enter row size :  3
Enter column size :  2
 1
 2
 3
 4
 5
 6


[[1, 2], [3, 4], [5, 6]]


### Get row size and column size from the user
####  Method 2

In [32]:
a = list(map(int, input().split()))
mat = np.array(a).reshape(m,n)
mat

 1 2 3 4 5 6


array([[1, 2],
       [3, 4],
       [5, 6]])

### Trace

In [30]:
n1.trace()

5

In [47]:
np.linalg.matrix_rank(n1)

2

In [51]:
np.linalg.eig(n1)

EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))