In [20]:
import numpy as np

## Write a numpy program to create two arrays and print it and make elemnt wise compariosn(<.>,<=,>=)

In [35]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.greater(a,b)


array([False, False, False, False, False])

In [37]:
np.less(a,b)

array([ True,  True,  True,  True,  True])

In [39]:
np.greater_equal(a,b)

array([False, False, False, False, False])

In [41]:
np.less_equal(a,b)

array([ True,  True,  True,  True,  True])

In [45]:
np.equal(a,b)

array([False, False, False, False, False])

## Write a numpy program to create even array starting from 50 to 90

In [48]:
x = np.arange(50,90,2)
x

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88])

## create a numpy program to generate a 4*4 identity matrix

In [55]:
y = np.identity(4,dtype=int)
y

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

## write a program to create a 5*5 zero matrix with elements on the main diagonal = 1,2,3,4,5 . others should be 0

In [65]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])