In [8]:
import numpy as np

## Write a numpy program to create two arrays and print it and make elemnt wise compariosn(<.>,<=,>=)

In [35]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.greater(a,b)


array([False, False, False, False, False])

In [37]:
np.less(a,b)

array([ True,  True,  True,  True,  True])

In [39]:
np.greater_equal(a,b)

array([False, False, False, False, False])

In [41]:
np.less_equal(a,b)

array([ True,  True,  True,  True,  True])

In [45]:
np.equal(a,b)

array([False, False, False, False, False])

## Write a numpy program to create even array starting from 50 to 90

In [48]:
x = np.arange(50,90,2)
x

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88])

## create a numpy program to generate a 4*4 identity matrix

In [55]:
y = np.identity(4,dtype=int)
y

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

## write a program to create a 5*5 zero matrix with elements on the main diagonal = 1,2,3,4,5 . others should be 0

In [65]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### Write a numpy program to create a vector with values 0 to 20  and change the sign of the number in the range from 9 to 15.


In [16]:
n = np.arange(0,21)
l = []
for i in n:
    if i>=9 and i<=15:
        i=i*-1
    l.append(i)
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, -9, -10, -11, -12, -13, -14, -15, 16, 17, 18, 19, 20]


### Write a numpy program to compute sum of all the elements, sum of each col and sum of each row of an array


In [71]:
#matrix = np.random.randint(0,20, size=(3,3))

"""m = int(input("Enter number of rows : "))
n = int(input("Enter number of column : "))
matrix = []
print("Enter the matrix")
for i in range(m):
    row = []
    for j in range(n):
        a = int(input())
        row.append(a)
    matrix.append(row)"""

a = list(map(int, input().split()))
matrix = np.array(a).reshape(m,n)
matrix

matrix_sum = np.sum(matrix)

matrix_row_sum = np.sum(matrix,axis=1)

matrix_col_sum = np.sum(matrix,axis=0)

print("Matrix is ")
print(matrix)

print("Matrix sum")
print(matrix_sum)

print("Sum of each row")
print(matrix_row_sum)

print("Sum of each column")
print(matrix_col_sum)
type(matrix)

 1 2 3 4 5 6


Matrix is 
[[1 2]
 [3 4]
 [5 6]]
Matrix sum
21
Sum of each row
[ 3  7 11]
Sum of each column
[ 9 12]


numpy.ndarray

### Write a numpy program to save a given array to a text file and load it.


In [40]:
m1 = np.random.randint(0,20, size=(3,3))

fname = 'array1.txt'

np.savetxt(fname,m1)

a = np.loadtxt(fname)

print(a)

[[17. 19. 17.]
 [16.  1.  2.]
 [19.  8. 17.]]


### Write a numpy program to check whether two arrays are equal..element wise comp


In [46]:
#mat1 = np.random.randint(0,20, size=(3,3))
#mat2 = np.random.randint(0,20, size=(3,3))
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])
res = matrix1 == matrix2
print(res)

[[False False False]
 [False  True False]
 [False False False]]



### Write a numpy program to create a 4*4 array, create a new array from the set array by swapping first and last rows .


In [56]:
n = np.random.randint(0,10, size=(4,4))
print("Before swapping")
print(n)

print("After swapping")
n[[0, -1]] = n[[-1, 0]] 
print(n)

Before swapping
[[6 7 1 6]
 [4 1 2 6]
 [3 0 6 1]
 [6 6 2 9]]
After swapping
[[6 6 2 9]
 [4 1 2 6]
 [3 0 6 1]
 [6 7 1 6]]



### Write numpy program to multiply two arrays of same size element by element.

In [48]:
mat = matrix1*matrix2
mat

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])